// RGB triplets (0–255) mirroring the hex accent tokens in globals.css.
// Kept as module-level constants (not inline array literals at call
// sites) so each one is a stable reference across renders — HeroCanvas
// depends on this identity to know when to actually rebuild its WebGL
// scene vs. re-render for an unrelated reason.
export const ACCENT_RED: readonly [number, number, number] = [0xd8, 0x3b, 0x32]; // accent-red   #D83B32
export const ACCENT_HARNESS: readonly [number, number, number] = [0x4f, 0x3f, 0xd8]; // accent-harness #4F3FD8
export const ACCENT_CHAT: readonly [number, number, number] = [0xd8, 0x8a, 0x3b]; // accent-chat  #D88A3B

export type AccentName = 'red' | 'harness' | 'chat';

export const ACCENT_RGB: Record<AccentName, readonly [number, number, number]> = {
  red: ACCENT_RED,
  harness: ACCENT_HARNESS,
  chat: ACCENT_CHAT,
};

// Class-name suffixes for the .btn-pill-glass-* ring modifiers in
// globals.css, keyed the same way.
export const ACCENT_GLASS_CLASS: Record<AccentName, string> = {
  red: 'btn-pill-glass-red',
  harness: 'btn-pill-glass-harness',
  chat: 'btn-pill-glass-chat',
};

// Tailwind utility fragments for each accent's text/bg/border/soft
// tokens, generated by globals.css's @theme block (bg-accent-harness,
// text-accent-chat, etc.). Centralized here so pages pick the right
// classes by name instead of re-deriving the string each time.
export const ACCENT_TEXT_CLASS: Record<AccentName, string> = {
  red: 'text-accent-red',
  harness: 'text-accent-harness',
  chat: 'text-accent-chat',
};

// Complete, un-concatenated "hover:text-accent-x" strings — Tailwind's
// content scanner needs each full class string to appear literally
// somewhere in the source. Building this at runtime as
// `hover:${ACCENT_TEXT_CLASS[x]}` would never match, since "hover:"
// and "text-accent-x" only become adjacent after string interpolation,
// never as literal source text.
export const ACCENT_HOVER_TEXT_CLASS: Record<AccentName, string> = {
  red: 'hover:text-accent-red',
  harness: 'hover:text-accent-harness',
  chat: 'hover:text-accent-chat',
};
